# Imported from https://gist.github.com/filipemeneses/5a7d04a8198bfb1a756060c08d081805
# COUNTRIES = {c.get('iso'): {'name': c['name'], 'flag': c['flag']} for c in [...]}
COUNTRIES = {
    'AD': {'name': 'Andorra', 'flag': '🇦🇩'}, 'AE': {'name': 'United Arab Emirates', 'flag': '🇦🇪'},
    'AF': {'name': 'Afghanistan', 'flag': '🇦🇫'}, 'AG': {'name': 'Antigua and Barbuda', 'flag': '🇦🇬'},
    'AI': {'name': 'Anguilla', 'flag': '🇦🇮'}, 'AL': {'name': 'Albania', 'flag': '🇦🇱'},
    'AM': {'name': 'Armenia', 'flag': '🇦🇲'}, 'AO': {'name': 'Angola', 'flag': '🇦🇴'},
    'AQ': {'name': 'Antarctica', 'flag': '🇦🇶'}, 'AR': {'name': 'Argentina', 'flag': '🇦🇷'},
    'AS': {'name': 'American Samoa', 'flag': '🇦🇸'}, 'AT': {'name': 'Austria', 'flag': '🇦🇹'},
    'AU': {'name': 'Australia', 'flag': '🇦🇺'}, 'AW': {'name': 'Aruba', 'flag': '🇦🇼'},
    'AX': {'name': 'Åland Islands', 'flag': '🇦🇽'}, 'AZ': {'name': 'Azerbaijan', 'flag': '🇦🇿'},
    'BA': {'name': 'Bosnia and Herzegovina', 'flag': '🇧🇦'}, 'BB': {'name': 'Barbados', 'flag': '🇧🇧'},
    'BD': {'name': 'Bangladesh', 'flag': '🇧🇩'}, 'BE': {'name': 'Belgium', 'flag': '🇧🇪'},
    'BF': {'name': 'Burkina Faso', 'flag': '🇧🇫'}, 'BG': {'name': 'Bulgaria', 'flag': '🇧🇬'},
    'BH': {'name': 'Bahrain', 'flag': '🇧🇭'}, 'BI': {'name': 'Burundi', 'flag': '🇧🇮'},
    'BJ': {'name': 'Benin', 'flag': '🇧🇯'}, 'BL': {'name': 'Saint Barthélemy', 'flag': '🇧🇱'},
    'BM': {'name': 'Bermuda', 'flag': '🇧🇲'}, 'BN': {'name': 'Brunei Darussalam', 'flag': '🇧🇳'},
    'BO': {'name': 'Bolivia', 'flag': '🇧🇴'}, 'BQ': {'name': 'Bonaire, Sint Eustatius and Saba', 'flag': '🇧🇶'},
    'BR': {'name': 'Brazil', 'flag': '🇧🇷'}, 'BS': {'name': 'Bahamas', 'flag': '🇧🇸'},
    'BT': {'name': 'Bhutan', 'flag': '🇧🇹'}, 'BV': {'name': 'Bouvet Island', 'flag': '🇧🇻'},
    'BW': {'name': 'Botswana', 'flag': '🇧🇼'}, 'BY': {'name': 'Belarus', 'flag': '🇧🇾'},
    'BZ': {'name': 'Belize', 'flag': '🇧🇿'}, 'CA': {'name': 'Canada', 'flag': '🇨🇦'},
    'CC': {'name': 'Cocos (Keeling) Islands', 'flag': '🇨🇨'}, 'CD': {'name': 'Congo', 'flag': '🇨🇩'},
    'CF': {'name': 'Central African Republic', 'flag': '🇨🇫'}, 'CG': {'name': 'Congo', 'flag': '🇨🇬'},
    'CH': {'name': 'Switzerland', 'flag': '🇨🇭'}, 'CI': {'name': "Côte D'Ivoire", 'flag': '🇨🇮'},
    'CK': {'name': 'Cook Islands', 'flag': '🇨🇰'}, 'CL': {'name': 'Chile', 'flag': '🇨🇱'},
    'CM': {'name': 'Cameroon', 'flag': '🇨🇲'}, 'CN': {'name': 'China', 'flag': '🇨🇳'},
    'CO': {'name': 'Colombia', 'flag': '🇨🇴'}, 'CR': {'name': 'Costa Rica', 'flag': '🇨🇷'},
    'CU': {'name': 'Cuba', 'flag': '🇨🇺'}, 'CV': {'name': 'Cape Verde', 'flag': '🇨🇻'},
    'CW': {'name': 'Curaçao', 'flag': '🇨🇼'}, 'CX': {'name': 'Christmas Island', 'flag': '🇨🇽'},
    'CY': {'name': 'Cyprus', 'flag': '🇨🇾'}, 'CZ': {'name': 'Czech Republic', 'flag': '🇨🇿'},
    'DE': {'name': 'Germany', 'flag': '🇩🇪'}, 'DJ': {'name': 'Djibouti', 'flag': '🇩🇯'},
    'DK': {'name': 'Denmark', 'flag': '🇩🇰'}, 'DM': {'name': 'Dominica', 'flag': '🇩🇲'},
    'DO': {'name': 'Dominican Republic', 'flag': '🇩🇴'}, 'DZ': {'name': 'Algeria', 'flag': '🇩🇿'},
    'EC': {'name': 'Ecuador', 'flag': '🇪🇨'}, 'EE': {'name': 'Estonia', 'flag': '🇪🇪'},
    'EG': {'name': 'Egypt', 'flag': '🇪🇬'}, 'EH': {'name': 'Western Sahara', 'flag': '🇪🇭'},
    'ER': {'name': 'Eritrea', 'flag': '🇪🇷'}, 'ES': {'name': 'Spain', 'flag': '🇪🇸'},
    'ET': {'name': 'Ethiopia', 'flag': '🇪🇹'}, 'FI': {'name': 'Finland', 'flag': '🇫🇮'},
    'FJ': {'name': 'Fiji', 'flag': '🇫🇯'}, 'FK': {'name': 'Falkland Islands (Malvinas)', 'flag': '🇫🇰'},
    'FM': {'name': 'Micronesia', 'flag': '🇫🇲'}, 'FO': {'name': 'Faroe Islands', 'flag': '🇫🇴'},
    'FR': {'name': 'France', 'flag': '🇫🇷'}, 'GA': {'name': 'Gabon', 'flag': '🇬🇦'},
    'GB': {'name': 'United Kingdom', 'flag': '🇬🇧'}, 'GD': {'name': 'Grenada', 'flag': '🇬🇩'},
    'GE': {'name': 'Georgia', 'flag': '🇬🇪'}, 'GF': {'name': 'French Guiana', 'flag': '🇬🇫'},
    'GG': {'name': 'Guernsey', 'flag': '🇬🇬'}, 'GH': {'name': 'Ghana', 'flag': '🇬🇭'},
    'GI': {'name': 'Gibraltar', 'flag': '🇬🇮'}, 'GL': {'name': 'Greenland', 'flag': '🇬🇱'},
    'GM': {'name': 'Gambia', 'flag': '🇬🇲'}, 'GN': {'name': 'Guinea', 'flag': '🇬🇳'},
    'GP': {'name': 'Guadeloupe', 'flag': '🇬🇵'}, 'GQ': {'name': 'Equatorial Guinea', 'flag': '🇬🇶'},
    'GR': {'name': 'Greece', 'flag': '🇬🇷'}, 'GS': {'name': 'South Georgia', 'flag': '🇬🇸'},
    'GT': {'name': 'Guatemala', 'flag': '🇬🇹'}, 'GU': {'name': 'Guam', 'flag': '🇬🇺'},
    'GW': {'name': 'Guinea-Bissau', 'flag': '🇬🇼'}, 'GY': {'name': 'Guyana', 'flag': '🇬🇾'},
    'HK': {'name': 'Hong Kong', 'flag': '🇭🇰'}, 'HM': {'name': 'Heard Island and Mcdonald Islands', 'flag': '🇭🇲'},
    'HN': {'name': 'Honduras', 'flag': '🇭🇳'}, 'HR': {'name': 'Croatia', 'flag': '🇭🇷'},
    'HT': {'name': 'Haiti', 'flag': '🇭🇹'}, 'HU': {'name': 'Hungary', 'flag': '🇭🇺'},
    'ID': {'name': 'Indonesia', 'flag': '🇮🇩'}, 'IE': {'name': 'Ireland', 'flag': '🇮🇪'},
    'IL': {'name': 'Israel', 'flag': '🇮🇱'}, 'IM': {'name': 'Isle of Man', 'flag': '🇮🇲'},
    'IN': {'name': 'India', 'flag': '🇮🇳'}, 'IO': {'name': 'British Indian Ocean Territory', 'flag': '🇮🇴'},
    'IQ': {'name': 'Iraq', 'flag': '🇮🇶'}, 'IR': {'name': 'Iran', 'flag': '🇮🇷'}, 'IS': {'name': 'Iceland', 'flag': '🇮🇸'},
    'IT': {'name': 'Italy', 'flag': '🇮🇹'}, 'JE': {'name': 'Jersey', 'flag': '🇯🇪'},
    'JM': {'name': 'Jamaica', 'flag': '🇯🇲'}, 'JO': {'name': 'Jordan', 'flag': '🇯🇴'},
    'JP': {'name': 'Japan', 'flag': '🇯🇵'}, 'KE': {'name': 'Kenya', 'flag': '🇰🇪'},
    'KG': {'name': 'Kyrgyzstan', 'flag': '🇰🇬'}, 'KH': {'name': 'Cambodia', 'flag': '🇰🇭'},
    'KI': {'name': 'Kiribati', 'flag': '🇰🇮'}, 'KM': {'name': 'Comoros', 'flag': '🇰🇲'},
    'KN': {'name': 'Saint Kitts and Nevis', 'flag': '🇰🇳'}, 'KP': {'name': 'North Korea', 'flag': '🇰🇵'},
    'KR': {'name': 'South Korea', 'flag': '🇰🇷'}, 'KW': {'name': 'Kuwait', 'flag': '🇰🇼'},
    'KY': {'name': 'Cayman Islands', 'flag': '🇰🇾'}, 'KZ': {'name': 'Kazakhstan', 'flag': '🇰🇿'},
    'LA': {'name': "Lao People's Democratic Republic", 'flag': '🇱🇦'}, 'LB': {'name': 'Lebanon', 'flag': '🇱🇧'},
    'LC': {'name': 'Saint Lucia', 'flag': '🇱🇨'}, 'LI': {'name': 'Liechtenstein', 'flag': '🇱🇮'},
    'LK': {'name': 'Sri Lanka', 'flag': '🇱🇰'}, 'LR': {'name': 'Liberia', 'flag': '🇱🇷'},
    'LS': {'name': 'Lesotho', 'flag': '🇱🇸'}, 'LT': {'name': 'Lithuania', 'flag': '🇱🇹'},
    'LU': {'name': 'Luxembourg', 'flag': '🇱🇺'}, 'LV': {'name': 'Latvia', 'flag': '🇱🇻'},
    'LY': {'name': 'Libya', 'flag': '🇱🇾'}, 'MA': {'name': 'Morocco', 'flag': '🇲🇦'},
    'MC': {'name': 'Monaco', 'flag': '🇲🇨'}, 'MD': {'name': 'Moldova', 'flag': '🇲🇩'},
    'ME': {'name': 'Montenegro', 'flag': '🇲🇪'}, 'MF': {'name': 'Saint Martin (French Part)', 'flag': '🇲🇫'},
    'MG': {'name': 'Madagascar', 'flag': '🇲🇬'}, 'MH': {'name': 'Marshall Islands', 'flag': '🇲🇭'},
    'MK': {'name': 'Macedonia', 'flag': '🇲🇰'}, 'ML': {'name': 'Mali', 'flag': '🇲🇱'},
    'MM': {'name': 'Myanmar', 'flag': '🇲🇲'}, 'MN': {'name': 'Mongolia', 'flag': '🇲🇳'},
    'MO': {'name': 'Macao', 'flag': '🇲🇴'}, 'MP': {'name': 'Northern Mariana Islands', 'flag': '🇲🇵'},
    'MQ': {'name': 'Martinique', 'flag': '🇲🇶'}, 'MR': {'name': 'Mauritania', 'flag': '🇲🇷'},
    'MS': {'name': 'Montserrat', 'flag': '🇲🇸'}, 'MT': {'name': 'Malta', 'flag': '🇲🇹'},
    'MU': {'name': 'Mauritius', 'flag': '🇲🇺'}, 'MV': {'name': 'Maldives', 'flag': '🇲🇻'},
    'MW': {'name': 'Malawi', 'flag': '🇲🇼'}, 'MX': {'name': 'Mexico', 'flag': '🇲🇽'},
    'MY': {'name': 'Malaysia', 'flag': '🇲🇾'}, 'MZ': {'name': 'Mozambique', 'flag': '🇲🇿'},
    'NA': {'name': 'Namibia', 'flag': '🇳🇦'}, 'NC': {'name': 'New Caledonia', 'flag': '🇳🇨'},
    'NE': {'name': 'Niger', 'flag': '🇳🇪'}, 'NF': {'name': 'Norfolk Island', 'flag': '🇳🇫'},
    'NG': {'name': 'Nigeria', 'flag': '🇳🇬'}, 'NI': {'name': 'Nicaragua', 'flag': '🇳🇮'},
    'NL': {'name': 'Netherlands', 'flag': '🇳🇱'}, 'NO': {'name': 'Norway', 'flag': '🇳🇴'},
    'NP': {'name': 'Nepal', 'flag': '🇳🇵'}, 'NR': {'name': 'Nauru', 'flag': '🇳🇷'}, 'NU': {'name': 'Niue', 'flag': '🇳🇺'},
    'NZ': {'name': 'New Zealand', 'flag': '🇳🇿'}, 'OM': {'name': 'Oman', 'flag': '🇴🇲'},
    'PA': {'name': 'Panama', 'flag': '🇵🇦'}, 'PE': {'name': 'Peru', 'flag': '🇵🇪'},
    'PF': {'name': 'French Polynesia', 'flag': '🇵🇫'}, 'PG': {'name': 'Papua New Guinea', 'flag': '🇵🇬'},
    'PH': {'name': 'Philippines', 'flag': '🇵🇭'}, 'PK': {'name': 'Pakistan', 'flag': '🇵🇰'},
    'PL': {'name': 'Poland', 'flag': '🇵🇱'}, 'PM': {'name': 'Saint Pierre and Miquelon', 'flag': '🇵🇲'},
    'PN': {'name': 'Pitcairn', 'flag': '🇵🇳'}, 'PR': {'name': 'Puerto Rico', 'flag': '🇵🇷'},
    'PS': {'name': 'Palestinian Territory', 'flag': '🇵🇸'}, 'PT': {'name': 'Portugal', 'flag': '🇵🇹'},
    'PW': {'name': 'Palau', 'flag': '🇵🇼'}, 'PY': {'name': 'Paraguay', 'flag': '🇵🇾'},
    'QA': {'name': 'Qatar', 'flag': '🇶🇦'}, 'RE': {'name': 'Réunion', 'flag': '🇷🇪'},
    'RO': {'name': 'Romania', 'flag': '🇷🇴'}, 'RS': {'name': 'Serbia', 'flag': '🇷🇸'},
    'RU': {'name': 'Russia', 'flag': '🇷🇺'}, 'RW': {'name': 'Rwanda', 'flag': '🇷🇼'},
    'SA': {'name': 'Saudi Arabia', 'flag': '🇸🇦'}, 'SB': {'name': 'Solomon Islands', 'flag': '🇸🇧'},
    'SC': {'name': 'Seychelles', 'flag': '🇸🇨'}, 'SD': {'name': 'Sudan', 'flag': '🇸🇩'},
    'SE': {'name': 'Sweden', 'flag': '🇸🇪'}, 'SG': {'name': 'Singapore', 'flag': '🇸🇬'},
    'SH': {'name': 'Saint Helena, Ascension and Tristan Da Cunha', 'flag': '🇸🇭'},
    'SI': {'name': 'Slovenia', 'flag': '🇸🇮'}, 'SJ': {'name': 'Svalbard and Jan Mayen', 'flag': '🇸🇯'},
    'SK': {'name': 'Slovakia', 'flag': '🇸🇰'}, 'SL': {'name': 'Sierra Leone', 'flag': '🇸🇱'},
    'SM': {'name': 'San Marino', 'flag': '🇸🇲'}, 'SN': {'name': 'Senegal', 'flag': '🇸🇳'},
    'SO': {'name': 'Somalia', 'flag': '🇸🇴'}, 'SR': {'name': 'Suriname', 'flag': '🇸🇷'},
    'SS': {'name': 'South Sudan', 'flag': '🇸🇸'}, 'ST': {'name': 'Sao Tome and Principe', 'flag': '🇸🇹'},
    'SV': {'name': 'El Salvador', 'flag': '🇸🇻'}, 'SX': {'name': 'Sint Maarten (Dutch Part)', 'flag': '🇸🇽'},
    'SY': {'name': 'Syrian Arab Republic', 'flag': '🇸🇾'}, 'SZ': {'name': 'Swaziland', 'flag': '🇸🇿'},
    'TC': {'name': 'Turks and Caicos Islands', 'flag': '🇹🇨'}, 'TD': {'name': 'Chad', 'flag': '🇹🇩'},
    'TF': {'name': 'French Southern Territories', 'flag': '🇹🇫'}, 'TG': {'name': 'Togo', 'flag': '🇹🇬'},
    'TH': {'name': 'Thailand', 'flag': '🇹🇭'}, 'TJ': {'name': 'Tajikistan', 'flag': '🇹🇯'},
    'TK': {'name': 'Tokelau', 'flag': '🇹🇰'}, 'TL': {'name': 'Timor-Leste', 'flag': '🇹🇱'},
    'TM': {'name': 'Turkmenistan', 'flag': '🇹🇲'}, 'TN': {'name': 'Tunisia', 'flag': '🇹🇳'},
    'TO': {'name': 'Tonga', 'flag': '🇹🇴'}, 'TR': {'name': 'Turkey', 'flag': '🇹🇷'},
    'TT': {'name': 'Trinidad and Tobago', 'flag': '🇹🇹'}, 'TV': {'name': 'Tuvalu', 'flag': '🇹🇻'},
    'TW': {'name': 'Taiwan', 'flag': '🇹🇼'}, 'TZ': {'name': 'Tanzania', 'flag': '🇹🇿'},
    'UA': {'name': 'Ukraine', 'flag': '🇺🇦'}, 'UG': {'name': 'Uganda', 'flag': '🇺🇬'},
    'UM': {'name': 'United States Minor Outlying Islands', 'flag': '🇺🇲'}, 'US': {'name': 'United States', 'flag': '🇺🇸'},
    'UY': {'name': 'Uruguay', 'flag': '🇺🇾'}, 'UZ': {'name': 'Uzbekistan', 'flag': '🇺🇿'},
    'VA': {'name': 'Vatican City', 'flag': '🇻🇦'}, 'VC': {'name': 'Saint Vincent and The Grenadines', 'flag': '🇻🇨'},
    'VE': {'name': 'Venezuela', 'flag': '🇻🇪'}, 'VG': {'name': 'Virgin Islands, British', 'flag': '🇻🇬'},
    'VI': {'name': 'Virgin Islands, U.S.', 'flag': '🇻🇮'}, 'VN': {'name': 'Viet Nam', 'flag': '🇻🇳'},
    'VU': {'name': 'Vanuatu', 'flag': '🇻🇺'}, 'WF': {'name': 'Wallis and Futuna', 'flag': '🇼🇫'},
    'WS': {'name': 'Samoa', 'flag': '🇼🇸'}, 'XK': {'name': 'Kosovo', 'flag': '🇽🇰'},
    'YE': {'name': 'Yemen', 'flag': '🇾🇪'}, 'YT': {'name': 'Mayotte', 'flag': '🇾🇹'},
    'ZA': {'name': 'South Africa', 'flag': '🇿🇦'}, 'ZM': {'name': 'Zambia', 'flag': '🇿🇲'},
    'ZW': {'name': 'Zimbabwe', 'flag': '🇿🇼'},
    'GB-ENG': {'name': 'England', 'flag': '🏴\U000e0067\U000e0062\U000e0065\U000e006e\U000e0067\U000e007f'},
    'GB-SCT': {'name': 'Scotland', 'flag': '🏴\U000e0067\U000e0062\U000e0073\U000e0063\U000e0074\U000e007f'},
    'GB-WLS': {'name': 'Wales', 'flag': '🏴\U000e0067\U000e0062\U000e0077\U000e006c\U000e0073\U000e007f'}}
